CREATE TABLE training_apps (
  id TEXT PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  provider_name TEXT NOT NULL,
  category TEXT NOT NULL,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  country TEXT DEFAULT 'United States',
  price TEXT,
  description TEXT,
  website TEXT,
  email TEXT,
  phone TEXT,
  image_url TEXT,
  video_url TEXT,
  image_position INTEGER DEFAULT 50,
  hero_image_position INTEGER DEFAULT 50,
  photos TEXT,
  announcement_heading TEXT,
  announcement_text TEXT,
  announcement_image TEXT,
  announcement_heading_2 TEXT,
  announcement_text_2 TEXT,
  announcement_image_2 TEXT,
  announcement_heading_3 TEXT,
  announcement_text_3 TEXT,
  announcement_image_3 TEXT,
  about_author TEXT,
  featured BOOLEAN DEFAULT FALSE,
  user_id TEXT REFERENCES users(id),
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
