// ── Daily Playbook ───────────────────────────────────────────────────────────
export interface DailyTask {
  day: string;
  channel: string;
  task: string;
  details: string;
  platforms: string;
  timeEst: string;
  link?: string;
}
export const DAILY_TASKS: DailyTask[] = [
  { day: "Monday",    channel: "Social Media",    task: "Post TikTok/Reel #1",           details: "Player skill progression reel (Day 1 vs Day 30 format). Use trending audio. Caption: problem → solution → CTA to free trial",                                                                      platforms: "TikTok + IG Reels",   timeEst: "45 min", link: "https://www.tiktok.com/@thunderfutbol/video/7526003740982152478" },
  { day: "Monday",    channel: "Email Marketing", task: "Prep weekly email",              details: "Tuesday's email gets prepped Monday. Write subject line (A/B test), body copy, and CTA. Segment: active leads vs lapsed users",                                                                    platforms: "Go High Level",        timeEst: "45 min" },
  { day: "Monday",    channel: "Content / SEO",   task: "Publish blog post",             details: "1 SEO-optimized article per week. Alternate: comparison posts (DribbleUp vs Anytime), parent guides, training tips, coach resources",                                                               platforms: "Website Blog",         timeEst: "90 min" },
  { day: "Monday",    channel: "Paid Ads",         task: "Review weekend performance",    details: "Check Meta & Google ROAS, CPC, CTR. Pause underperformers. Scale winners. Adjust budgets for the week",                                                                                            platforms: "Meta + Google Ads",    timeEst: "30 min" },
  { day: "Tuesday",   channel: "Social Media",    task: "Post TikTok/Reel #2",           details: "Coach testimonial or parent reaction clip. Format: hook (3 sec) → story → result → CTA. Tag relevant soccer accounts",                                                                             platforms: "TikTok + IG Reels",   timeEst: "45 min" },
  { day: "Tuesday",   channel: "Email Marketing", task: "Send weekly broadcast",         details: "Send the email prepped Monday. Target: 30%+ open rate, 3%+ CTR. Include 1 clear CTA (free trial, upgrade, or seasonal offer)",                                                                     platforms: "Go High Level",        timeEst: "15 min" },
  { day: "Tuesday",   channel: "Partnerships",    task: "Coach/club outreach",           details: "Send 5 personalized DMs or emails to coaches/club directors. Pitch Club Champion affiliate program or team platform demo",                                                                           platforms: "Email + IG DM",        timeEst: "45 min" },
  { day: "Wednesday", channel: "Social Media",    task: "Post TikTok/Reel #3",           details: "Leaderboard spotlight — feature a top player. 'This week's #1 on the leaderboard trained 6 days straight 🔥'",                                                                                    platforms: "TikTok + IG Reels",   timeEst: "45 min" },
  { day: "Wednesday", channel: "Content / SEO",   task: "Podcast episode work",          details: "Record or edit The Inside Scoop episode. Guests: coaches, soccer parents, club directors, youth development experts",                                                                               platforms: "Podcast platforms",    timeEst: "90 min" },
  { day: "Wednesday", channel: "Social Media",    task: "Engage & comment",              details: "30 min engaging: reply to comments, engage on soccer parent hashtags, comment on coach/club posts, share UGC to stories",                                                                           platforms: "IG + TikTok + FB",    timeEst: "30 min" },
  { day: "Thursday",  channel: "Social Media",    task: "Post TikTok/Reel #4",           details: "Training tip / drill of the week. Quick 30-sec demo of a popular drill from the platform. 'Try this at home tonight 👇'",                                                                          platforms: "TikTok + IG Reels",   timeEst: "45 min" },
  { day: "Thursday",  channel: "Email Marketing", task: "Nurture sequence check",        details: "Review automated email sequences: welcome series, trial-to-paid, re-engagement, coach onboarding. Optimize low-performers",                                                                         platforms: "Go High Level",        timeEst: "30 min" },
  { day: "Thursday",  channel: "Paid Ads",         task: "Mid-week ad optimization",     details: "A/B test new creative. Test new audiences. Review funnel: ad → landing page → signup → paid. Fix any drop-off points",                                                                             platforms: "Meta + Google Ads",    timeEst: "45 min" },
  { day: "Thursday",  channel: "Affiliate",        task: "Ambassador check-in",          details: "Message top 5 affiliates with performance update. Share new assets. Ask for content/testimonials they can post",                                                                                   platforms: "Email + Slack",        timeEst: "30 min" },
  { day: "Friday",    channel: "Social Media",    task: "Post TikTok/Reel #5",           details: "Fun/viral format: soccer challenge, kid fails/wins compilation, 'POV: your kid after 30 days on Anytime Soccer'. Encourage shares",                                                                 platforms: "TikTok + IG Reels",   timeEst: "45 min" },
  { day: "Friday",    channel: "Content / SEO",   task: "Publish podcast episode",       details: "Upload and distribute The Inside Scoop. Write show notes with keywords. Share clips to social. Email subscribers",                                                                                  platforms: "Apple/Spotify + Site", timeEst: "45 min" },
  { day: "Friday",    channel: "Social Media",    task: "Weekly analytics review",       details: "Review weekly social metrics: follower growth, engagement rate, top-performing content, saves/shares. Document what worked",                                                                        platforms: "All platforms",        timeEst: "30 min" },
  { day: "Saturday",  channel: "Social Media",    task: "Weekend engagement post",       details: "Story poll, Q&A, or 'What are you training this weekend?' engagement post. Repost any UGC from parents/players",                                                                                   platforms: "IG Stories + FB",     timeEst: "20 min" },
  { day: "Saturday",  channel: "Content / SEO",   task: "Next week content planning",    details: "Plan next week's 5 videos (scripts, clips to repurpose). Draft blog topic. Prep email copy outline",                                                                                               platforms: "Planning doc",         timeEst: "45 min" },
  { day: "Sunday",    channel: "Social Media",    task: "Light engagement / UGC repost", details: "Repost any tagged content from families training over the weekend. Simple motivational post: 'Rest day? Or get 1% better? 💪'",                                                                    platforms: "IG + TikTok",          timeEst: "15 min" },
  { day: "Sunday",    channel: "Email Marketing", task: "Prep Monday email",             details: "Draft Monday's email if not done Saturday. Queue in Go High Level. Set A/B test for subject lines",                                                                                                platforms: "Go High Level",        timeEst: "20 min" },
];

// ── Monthly Plan ─────────────────────────────────────────────────────────────
export interface MonthlyRow {
  month: string; campaign: string; channel: string;
  keyActions: string; contentOutput: string; kpiTargets: string; budget: string;
}
export const MONTHLY_PLAN: MonthlyRow[] = [
  { month: "Mar 2026", campaign: "Platform Launch Push",    channel: "Social Media",    keyActions: "Launch TikTok; ramp to 5 posts/week; Day 1 vs Day 30 + parent reactions; 'Free 7-Day Challenge' campaign",                                         contentOutput: "20 TikTok/Reels; 4 IG carousel posts",                   kpiTargets: "2,500 TikTok followers; 50K impressions; 100 free trial signups",     budget: "$200" },
  { month: "Mar 2026", campaign: "Platform Launch Push",    channel: "Email Marketing", keyActions: "Migrate to Go High Level. Build welcome series (5 emails), trial-to-paid nurture (7 emails), re-engagement. Launch weekly newsletter",              contentOutput: "4 weekly emails; 12 automation emails built",             kpiTargets: "25%+ open rate; 3%+ CTR; 50 trial-to-paid conversions",              budget: "$100" },
  { month: "Mar 2026", campaign: "Platform Launch Push",    channel: "Content / SEO",   keyActions: "Publish 4 blog articles (1 comparison, 1 parent guide, 2 training tips). Record 4 podcast episodes",                                                contentOutput: "4 blogs; 4 podcasts; 20 social clips from podcast",       kpiTargets: "500+ organic blog visits; 200 podcast downloads/ep",                 budget: "$0" },
  { month: "Mar 2026", campaign: "Platform Launch Push",    channel: "Paid Ads",         keyActions: "Launch Meta awareness campaign targeting soccer parents (28–45). Test 3 creatives. Set up Google Search for 'youth soccer training app'",            contentOutput: "6 ad creatives; 2 landing pages",                        kpiTargets: "CPC <$1.50; 200+ free trial signups; ROAS baseline set",             budget: "$500" },
  { month: "Apr 2026", campaign: "Affiliate Launch",        channel: "Affiliate",        keyActions: "Launch Club Champion program. Recruit first 10 coach ambassadors. Provide marketing kit. Track first conversions",                                   contentOutput: "Ambassador kit; 10 personalized outreach emails; dashboard live", kpiTargets: "10 active affiliates; 25+ teams via referrals; $2K affiliate revenue", budget: "$0" },
  { month: "Apr 2026", campaign: "Affiliate Launch",        channel: "Social Media",    keyActions: "Maintain 5 posts/week. Add coach testimonial series. Run first 'Leaderboard Champion of the Week' spotlight series",                                 contentOutput: "20+ TikTok/Reels; 4 coach testimonials",                 kpiTargets: "5,000 followers; engagement >5%; 150 profile visits/day",            budget: "$200" },
  { month: "Apr 2026", campaign: "Affiliate Launch",        channel: "Email Marketing", keyActions: "Segment list by: free trial, paid annual, team/club, lapsed. Build targeted sequences for each. A/B test subject lines aggressively",                contentOutput: "4 weekly emails; 2 new automated sequences",             kpiTargets: "30%+ open rate; unsubscribe <0.5%; 75 conversions",                  budget: "$100" },
  { month: "Apr 2026", campaign: "Affiliate Launch",        channel: "Paid Ads",         keyActions: "Retarget website visitors. Lookalike audiences from existing subscribers. Test video ads (repurposed TikToks)",                                      contentOutput: "4 new video ad creatives; retarget audiences built",     kpiTargets: "Retarget CPC <$0.80; 300+ total trial signups to date",              budget: "$750" },
  { month: "May 2026", campaign: "Summer Camp Prep 🏕️",    channel: "Paid Ads",         keyActions: "Launch 'Summer Training Starts Now' campaign. Target: parents searching summer soccer camps, off-season training. Gift sub angle for camps",         contentOutput: "8 ad creatives; 3 summer landing pages; video testimonials",      kpiTargets: "ROAS >3x; 500+ new trials; CPC <$1.25",                             budget: "$1,500" },
  { month: "May 2026", campaign: "Summer Camp Prep 🏕️",    channel: "Email Marketing", keyActions: "Summer campaign email blast. 3-part series: 'Don't waste the off-season'. Reactivation sequence for lapsed users",                                  contentOutput: "4 weekly emails; 3-part summer series; re-engagement blast",     kpiTargets: "35%+ open rate on summer series; 100+ re-activations",               budget: "$100" },
  { month: "May 2026", campaign: "Summer Camp Prep 🏕️",    channel: "Content / SEO",   keyActions: "Publish 'Ultimate Summer Soccer Training Guide' (pillar). 4 supporting blog posts. Podcast series on off-season development",                        contentOutput: "1 pillar article; 4 blogs; 4 podcasts",                  kpiTargets: "1,000+ organic visits to pillar; 50+ backlinks/shares",              budget: "$0" },
  { month: "May 2026", campaign: "Summer Camp Prep 🏕️",    channel: "Social Media",    keyActions: "'30 Days of Summer Soccer' challenge. Daily prompt for players to post training clips. Feature best submissions",                                    contentOutput: "20+ TikTok/Reels; summer challenge launch; daily prompts", kpiTargets: "10K followers; 500+ challenge participants; viral potential",         budget: "$200" },
  { month: "Jun 2026", campaign: "Premium Tier Marketing",  channel: "Email Marketing", keyActions: "Premium tier launch announcement. Exclusive early-bird pricing. Drip campaign explaining premium features (AI reports, badges, video review)",         contentOutput: "Launch email; 5-part premium drip; upgrade CTA in all emails",   kpiTargets: "15%+ of existing subs upgrade; 200 premium sign-ups month 1",        budget: "$100" },
  { month: "Jun 2026", campaign: "Premium Tier Marketing",  channel: "Paid Ads",         keyActions: "Premium-focused ads: 'Get personalized training plans for your player'. Retarget free/annual users with upgrade messaging",                          contentOutput: "6 premium ad creatives; upgrade landing page",           kpiTargets: "Premium ROAS >4x; 100+ premium sign-ups from paid; CPC <$2.00",     budget: "$1,500" },
  { month: "Jun 2026", campaign: "Premium Tier Marketing",  channel: "Content / SEO",   keyActions: "Case study: how [Player] improved with personalized premium training. Blog series on why personalized training matters",                              contentOutput: "2 case studies; 4 blogs; 4 podcasts",                   kpiTargets: "Case study 1,000+ views; premium page ranks for 'personalized soccer training'", budget: "$0" },
  { month: "Jun 2026", campaign: "Premium Tier Marketing",  channel: "Social Media",    keyActions: "Premium feature reveal series. Before/after using AI progress reports. Parent testimonial: 'Finally I can see my kid's progress'",                    contentOutput: "20+ TikTok/Reels; premium showcase series",              kpiTargets: "15K followers; 1,000+ premium page visits from social",              budget: "$200" },
  { month: "Jul 2026", campaign: "Club SaaS Push",          channel: "Partnerships",    keyActions: "Direct outreach to 50 club directors. LinkedIn campaign targeting DOCs. Webinar: 'How top clubs use homework tracking to develop players faster'",     contentOutput: "50 outreach emails; webinar content; 1-pager PDF for clubs",     kpiTargets: "5 club demo meetings; 2 signed club contracts; 50+ webinar attendees", budget: "$300" },
  { month: "Jul 2026", campaign: "Club SaaS Push",          channel: "Email Marketing", keyActions: "B2B email sequence for club directors. Highlight: homework tracking, leaderboards, parent engagement, ROI per player",                               contentOutput: "6-part B2B drip; club-specific landing page",            kpiTargets: "20%+ open rate on B2B; 10 demo requests",                           budget: "$100" },
  { month: "Jul 2026", campaign: "Club SaaS Push",          channel: "Content / SEO",   keyActions: "Publish 'The Club Director's Guide to Digital Player Development'. White paper. Podcast episode with a club director testimonial",                    contentOutput: "White paper; 4 blogs; 4 podcasts; club-focused SEO",    kpiTargets: "White paper 200+ downloads; club keyword rankings improve",          budget: "$0" },
  { month: "Jul 2026", campaign: "Club SaaS Push",          channel: "Social Media",    keyActions: "Club success stories. 'This club assigned 500 homework sessions last month' graphics. Coach reaction content",                                        contentOutput: "20+ TikTok/Reels; 4 club-focused posts",                kpiTargets: "20K followers; club directors engaging in comments/DMs",             budget: "$200" },
  { month: "Aug 2026", campaign: "Fall Season Campaign 🍂", channel: "Paid Ads",         keyActions: "Full-scale fall registration campaign. 'Train before tryouts'. Retarget all summer visitors. Increase budget Aug–Sep",                               contentOutput: "10 ad creatives; tryout-themed landing pages; video ads",kpiTargets: "ROAS >3.5x; 1,000+ new signups; $25K+ revenue from campaign",       budget: "$3,000" },
  { month: "Aug 2026", campaign: "Fall Season Campaign 🍂", channel: "Email Marketing", keyActions: "'Fall Season Prep' series to full list. Segment by age group. Coach-specific emails. Countdown urgency: 'Tryouts in X weeks'",                       contentOutput: "4 weekly emails; fall prep series; coach segment blast", kpiTargets: "40%+ open rate; 200+ conversions; coach segment: 15%+ CTR",          budget: "$100" },
  { month: "Aug 2026", campaign: "Fall Season Campaign 🍂", channel: "Social Media",    keyActions: "Tryout prep content: 'Top 5 skills scouts look for'. Parent anxiety content. Daily countdown posts",                                                  contentOutput: "25+ TikTok/Reels; tryout mini-series",                  kpiTargets: "25K followers; tryout content goes semi-viral (50K+ views)",         budget: "$200" },
  { month: "Aug 2026", campaign: "Fall Season Campaign 🍂", channel: "Content / SEO",   keyActions: "'How to Prepare for Fall Soccer Tryouts' pillar article. Supporting blogs on position-specific prep. Podcast with club tryout evaluator",             contentOutput: "1 pillar article; 4 blogs; 4 podcasts",                  kpiTargets: "2,000+ organic visits to tryout pillar; top 3 for 'soccer tryout prep'", budget: "$0" },
  { month: "Sep 2026", campaign: "Tournaments & Intl",      channel: "Tournament",       keyActions: "ECNL / US Club Soccer tournament booth. QR code free trial cards. Branded giveaways. Live demos at booth",                                           contentOutput: "Booth materials; 500 QR cards; giveaway items; demo script",     kpiTargets: "50+ teams signed up; 750+ player leads; 200 on-site conversions",   budget: "$2,500" },
  { month: "Sep 2026", campaign: "Tournaments & Intl",      channel: "Social Media",    keyActions: "Live tournament content. Behind-the-scenes booth setup. Player spotlights. Real-time engagement",                                                     contentOutput: "15 TikToks/Reels from tournament; stories all weekend",  kpiTargets: "30K followers; tournament content 100K+ impressions",               budget: "$200" },
  { month: "Sep 2026", campaign: "Tournaments & Intl",      channel: "Email Marketing", keyActions: "Post-tournament follow-up sequence for all leads. 'Great meeting you at [Tournament]!' → free trial → paid nurture",                                  contentOutput: "Tournament follow-up sequence (5 emails); lead import",  kpiTargets: "40%+ open rate on tournament leads; 25%+ trial-to-paid",            budget: "$100" },
  { month: "Oct 2026", campaign: "AI Coach Buzz",           channel: "PR / Outreach",   keyActions: "Pre-launch PR for AI virtual coach. Pitch to soccer media (SoccerWire, TopDrawerSoccer). Teaser content on social. Beta waitlist",                    contentOutput: "Press release; 3 media pitches; teaser video; beta landing page", kpiTargets: "3+ media features; 500+ beta waitlist signups",                     budget: "$0" },
  { month: "Oct 2026", campaign: "AI Coach Buzz",           channel: "Social Media",    keyActions: "AI coach teaser campaign: 'Something big is coming'. Beta user reactions. Behind-the-scenes of AI analyzing training clips",                          contentOutput: "20+ TikToks/Reels; AI teaser series; beta user testimonials",    kpiTargets: "35K followers; teaser videos 200K+ combined views",                 budget: "$200" },
  { month: "Oct 2026", campaign: "AI Coach Buzz",           channel: "Content / SEO",   keyActions: "'How AI Is Changing Youth Soccer Development' blog series. Podcast on tech in youth sports. Position as innovation leader",                            contentOutput: "4 blogs; 4 podcasts; thought leadership content",        kpiTargets: "AI blog posts rank for 'AI soccer training'; 1,500+ organic visits", budget: "$0" },
  { month: "Nov 2026", campaign: "Holiday Campaign 🎁",     channel: "Paid Ads",         keyActions: "'Give the Gift of Better Soccer' full campaign. Gift subscriptions. Black Friday: 50% off annual. Cyber Monday: free premium month",                  contentOutput: "12 holiday ad creatives; gift landing page; BF/CM pages", kpiTargets: "ROAS >4x; 2,000+ gift subs; $50K+ holiday revenue",                budget: "$5,000" },
  { month: "Nov 2026", campaign: "Holiday Campaign 🎁",     channel: "Email Marketing", keyActions: "Holiday gift guide email. BF early access for subscribers. 12-day countdown to Christmas. Gift-a-subscription CTA in every email",                    contentOutput: "8+ emails in Nov; gift guide; BF sequence; countdown series",    kpiTargets: "45%+ open rate on BF email; 500+ gift subs from email",             budget: "$100" },
  { month: "Nov 2026", campaign: "Holiday Campaign 🎁",     channel: "Social Media",    keyActions: "'Gift Guide for Soccer Kids' content. Countdown to BF deals. Unboxing-style content for merch bundles. Parent testimonial content",                    contentOutput: "25+ TikToks/Reels; holiday-themed content; BF countdown",kpiTargets: "40K followers; holiday content 300K+ impressions",                  budget: "$200" },
  { month: "Nov 2026", campaign: "Holiday Campaign 🎁",     channel: "Content / SEO",   keyActions: "'Best Gifts for Youth Soccer Players 2026' SEO article. Gift guide blog. Podcast holiday special",                                                    contentOutput: "1 gift guide pillar; 4 blogs; 2 podcast specials",      kpiTargets: "Gift guide ranks page 1; 5,000+ organic visits Nov-Dec",            budget: "$0" },
  { month: "Dec 2026", campaign: "Holiday Peak + Intl",     channel: "Paid Ads",         keyActions: "Final holiday push through Dec 20. Last-minute gift messaging. Shift budget to international pilot markets (UK, Australia)",                          contentOutput: "6 last-chance creatives; 4 international test ads",     kpiTargets: "Holiday total $50K+ revenue; International: 100+ signups from ads", budget: "$3,000" },
  { month: "Dec 2026", campaign: "Holiday Peak + Intl",     channel: "Email Marketing", keyActions: "Last-chance holiday emails. New Year prep: 'Start 2027 as a better player'. International welcome sequence. Year-end subscriber appreciation",         contentOutput: "6 emails; NYE prep series; international welcome sequence",      kpiTargets: "Holiday conversion peak; 200+ NYE prep signups",                    budget: "$100" },
  { month: "Dec 2026", campaign: "Holiday Peak + Intl",     channel: "Partnerships",    keyActions: "Finalize 5+ international football academy partnerships. Onboard pilot clubs in UK/Australia. Co-marketing agreements",                                contentOutput: "Partnership agreements; co-branded materials; onboarding docs",  kpiTargets: "5 signed international partners; 500+ international players onboarded", budget: "$500" },
  { month: "Jan 2027", campaign: "AI Coach Launch 🤖",      channel: "PR / Outreach",   keyActions: "Full AI coach launch PR push. Press releases to soccer + edtech publications. Influencer gifting. Podcast media tour",                                contentOutput: "Press release; 10 media pitches; 20 influencer kits; guest appearances", kpiTargets: "5+ major publications; 3+ influencer posts; 10K+ referral visits",  budget: "$1,000" },
  { month: "Jan 2027", campaign: "AI Coach Launch 🤖",      channel: "Social Media",    keyActions: "AI coach launch content blitz. Demo videos showing analysis. User reaction content. 'Upload your clip, get a plan in 60 seconds' format",              contentOutput: "30+ TikToks/Reels; AI demo series; user testimonials",  kpiTargets: "50K followers; AI launch content 500K+ impressions",                budget: "$500" },
  { month: "Jan 2027", campaign: "AI Coach Launch 🤖",      channel: "Email Marketing", keyActions: "AI coach announcement to full list. Upgrade campaign standard → premium. Exclusive early adopter benefits. Success stories from beta",                 contentOutput: "Launch email; 5-part AI feature drip; upgrade campaign", kpiTargets: "1,000+ AI coach sign-ups; 20%+ standard-to-premium upgrades",        budget: "$100" },
  { month: "Jan 2027", campaign: "AI Coach Launch 🤖",      channel: "Paid Ads",         keyActions: "AI coach as hero creative. 'Your kid's personal AI soccer coach for $149/yr'. Video demos in ads. Target tech-savvy soccer parents",                  contentOutput: "8 AI-focused ad creatives; new premium landing page",   kpiTargets: "ROAS >5x; CPA for premium <$30; 500+ premium signups from paid",    budget: "$3,000" },
  { month: "Feb 2027", campaign: "Brand Refresh + Spring",  channel: "Brand / UX",      keyActions: "New brand identity rollout. Updated logo applications. Refreshed social templates. New email templates matching updated brand. Consistency audit",     contentOutput: "Updated brand guidelines; new social + email templates", kpiTargets: "Brand recognition survey improvement; consistent look across all channels", budget: "$2,000" },
  { month: "Feb 2027", campaign: "Brand Refresh + Spring",  channel: "Paid Ads",         keyActions: "Spring season prep campaign. 'New year, new skills'. Updated creative with new brand identity. Retarget Jan leads",                                   contentOutput: "10 new-brand ad creatives; spring landing pages",       kpiTargets: "ROAS >3.5x; 800+ new signups; brand refresh improves CTR by 20%+", budget: "$2,500" },
  { month: "Feb 2027", campaign: "Brand Refresh + Spring",  channel: "Email Marketing", keyActions: "Spring training series. Brand refresh announcement email. Re-engage full list with fresh design. Spring early-bird offers for teams/clubs",             contentOutput: "4 weekly emails; spring series; brand announcement",    kpiTargets: "40%+ open rate on brand reveal; 150+ spring conversions",           budget: "$100" },
  { month: "Feb 2027", campaign: "Brand Refresh + Spring",  channel: "Social Media",    keyActions: "Brand refresh reveal. 'Same mission, elevated experience'. Spring content push. Maintain 5 posts/week with new templates",                             contentOutput: "20+ TikToks/Reels; brand reveal post; spring content",  kpiTargets: "55K followers; brand reveal post 50K+ impressions",                 budget: "$200" },
  { month: "Mar 2027", campaign: "Scale Everything",        channel: "Paid Ads",         keyActions: "Scale all proven campaigns to 2x budget. Automate winning creatives. Expand to YouTube pre-roll ads. International paid expansion",                    contentOutput: "YouTube ads; scaled Meta campaigns; international ads",  kpiTargets: "Overall ROAS >3x at 2x spend; 1,500+ monthly signups",              budget: "$5,000" },
  { month: "Mar 2027", campaign: "Scale Everything",        channel: "Partnerships",    keyActions: "B2B sales push: 50+ club target. Conference attendance (United Soccer Coaches). Referral partnerships with soccer equipment brands",                    contentOutput: "Conference booth; 50 club outreach emails; 3 brand partnerships", kpiTargets: "50+ club contracts; 3 brand partnerships signed",                   budget: "$3,000" },
  { month: "Apr–Jun 2027", campaign: "🎯 $1M ARR Sprint",  channel: "All Channels",    keyActions: "Optimize top-performing channels. Cut underperformers. Double down on highest-ROI activities. Ensure all channels working toward $1M+ ARR",            contentOutput: "Monthly channel performance reviews; quarterly strategy audit",  kpiTargets: "Verified $83K+/month across all channels = $1M+ ARR run rate",     budget: "Varies" },
];

// ── Annual Calendar ──────────────────────────────────────────────────────────
export interface AnnualRow {
  quarter: string; month: string; campaign: string;
  socialGoal: string; emailGoal: string; adsGoal: string;
  contentGoal: string; partnershipsGoal: string;
  budget: string; cumulative: string; revenueTarget: string;
}
export const ANNUAL_CALENDAR: AnnualRow[] = [
  { quarter: "Q1", month: "Mar 2026", campaign: "Platform Launch",   socialGoal: "Launch TikTok; 2,500 followers; 20 posts",                     emailGoal: "Go High Level live; welcome series; 4 newsletters",                   adsGoal: "Meta + Google launch; 200 trials; baseline ROAS",            contentGoal: "4 blogs; 4 podcasts; comparison SEO",            partnershipsGoal: "—",                              budget: "$1,000",  cumulative: "$1,000",  revenueTarget: "$8,000" },
  { quarter: "Q1", month: "Apr 2026", campaign: "Affiliate Launch",   socialGoal: "5,000 followers; coach testimonials series",                   emailGoal: "List segmentation; 30%+ opens; A/B testing",                         adsGoal: "Retargeting live; video ads; 300 trials",              contentGoal: "4 blogs; 4 podcasts; SEO optimization",          partnershipsGoal: "10 affiliates; Club Champion live",         budget: "$1,050",  cumulative: "$2,050",  revenueTarget: "$12,000" },
  { quarter: "Q1", month: "May 2026", campaign: "Summer Campaign",    socialGoal: "10,000 followers; 30-Day Challenge launch",                    emailGoal: "Summer series; re-engagement; 35%+ opens",                           adsGoal: "Summer campaign; ROAS >3x; 500+ trials",              contentGoal: "Summer pillar content; 4 blogs; 4 pods",         partnershipsGoal: "25+ teams via affiliates",                  budget: "$1,800",  cumulative: "$3,850",  revenueTarget: "$20,000" },
  { quarter: "Q2", month: "Jun 2026", campaign: "Premium Launch",     socialGoal: "15,000 followers; premium feature showcases",                  emailGoal: "Premium drip; upgrade campaign; 15% upgrades",                       adsGoal: "Premium ads; ROAS >4x; CPC <$2.00",                   contentGoal: "2 case studies; 4 blogs; 4 pods",                partnershipsGoal: "Affiliate growth to 20+",                  budget: "$1,800",  cumulative: "$5,650",  revenueTarget: "$28,000" },
  { quarter: "Q2", month: "Jul 2026", campaign: "Club SaaS Push",     socialGoal: "20,000 followers; club success stories",                       emailGoal: "B2B sequence; club director targeting",                               adsGoal: "Maintain consumer; test club ads",                    contentGoal: "White paper; club SEO; 4 pods",                  partnershipsGoal: "50 club outreach; 5 demos; 2 signed",      budget: "$600",   cumulative: "$6,250",  revenueTarget: "$32,000" },
  { quarter: "Q2", month: "Aug 2026", campaign: "Fall Campaign",      socialGoal: "25,000 followers; tryout prep content",                        emailGoal: "Fall prep series; coach segment; 40%+ opens",                        adsGoal: "Fall campaign; ROAS >3.5x; 1,000 signups",            contentGoal: "Tryout pillar content; 4 blogs",                 partnershipsGoal: "Club onboarding continued",                 budget: "$3,300",  cumulative: "$9,550",  revenueTarget: "$45,000" },
  { quarter: "Q3", month: "Sep 2026", campaign: "Tournament + Intl",  socialGoal: "30,000 followers; live tournament content",                    emailGoal: "Tournament follow-up sequence; 40%+ opens",                          adsGoal: "Maintain; retarget tournament leads",                  contentGoal: "4 blogs; 4 pods; thought leadership",            partnershipsGoal: "Tournament booth; 50+ teams; intl research",budget: "$2,800",  cumulative: "$12,350", revenueTarget: "$40,000" },
  { quarter: "Q3", month: "Oct 2026", campaign: "AI Coach Buzz",      socialGoal: "35,000 followers; AI teaser campaign",                         emailGoal: "Regular cadence; AI waitlist campaign",                               adsGoal: "Regular cadence; test AI teaser ads",                  contentGoal: "AI + youth sports blog series; 4 pods",          partnershipsGoal: "PR outreach; beta partnerships",            budget: "$200",   cumulative: "$12,550", revenueTarget: "$38,000" },
  { quarter: "Q3", month: "Nov 2026", campaign: "Holiday Campaign",   socialGoal: "40,000 followers; holiday + BF content",                       emailGoal: "BF email; gift guide; countdown; 45%+ opens",                        adsGoal: "Holiday: ROAS >4x; BF/CM push; $50K rev",             contentGoal: "Gift guide pillar; holiday SEO",                 partnershipsGoal: "Influencer gifting",                        budget: "$5,300",  cumulative: "$17,850", revenueTarget: "$60,000" },
  { quarter: "Q4", month: "Dec 2026", campaign: "Holiday + Intl",     socialGoal: "42,000 followers; maintain momentum",                          emailGoal: "Last-chance; NYE prep; intl welcome",                                adsGoal: "Final holiday; intl pilot ads",                        contentGoal: "Year-end recap content",                         partnershipsGoal: "5 intl academy partners",                  budget: "$3,600",  cumulative: "$21,450", revenueTarget: "$55,000" },
  { quarter: "Q4", month: "Jan 2027", campaign: "AI Coach Launch",    socialGoal: "50,000 followers; AI launch blitz",                            emailGoal: "AI announcement; upgrade campaign; 1K signups",                      adsGoal: "AI hero ads; ROAS >5x; premium focus",                 contentGoal: "PR coverage; 5+ publications",                   partnershipsGoal: "Influencer partnerships; media tour",       budget: "$4,600",  cumulative: "$26,050", revenueTarget: "$65,000" },
  { quarter: "Q4", month: "Feb 2027", campaign: "Brand + Spring",     socialGoal: "55,000 followers; brand refresh reveal",                       emailGoal: "Spring series; brand reveal; 40%+ opens",                            adsGoal: "Spring campaign; new brand creative",                  contentGoal: "4 blogs; 4 pods; refreshed templates",           partnershipsGoal: "Club expansion push",                      budget: "$4,800",  cumulative: "$30,850", revenueTarget: "$60,000" },
  { quarter: "Q5", month: "Mar 2027", campaign: "Scale",              socialGoal: "60,000+ followers; all channels humming",                      emailGoal: "Optimized sequences; 35%+ avg open rate",                            adsGoal: "Scale 2x; YouTube ads; ROAS >3x at scale",             contentGoal: "SEO authority; top rankings",                    partnershipsGoal: "50+ clubs; 3 brand partnerships",          budget: "$8,000",  cumulative: "$38,850", revenueTarget: "$75,000" },
  { quarter: "Q5", month: "Apr–Jun 27", campaign: "🎯 $1M ARR",     socialGoal: "75,000+ followers; brand authority",                           emailGoal: "Mature email engine; predictable conversions",                       adsGoal: "Proven paid machine; $5+ ROAS",                        contentGoal: "Organic traffic: 10K+/month",                    partnershipsGoal: "100+ clubs; intl expansion",               budget: "$10,000", cumulative: "$48,850", revenueTarget: "$85,000" },
];

// ── Action Plan ──────────────────────────────────────────────────────────────
export type ActionStatus = "Not Started" | "In Progress" | "Done" | "Paused";
export interface ActionRow {
  id: number; quarter: string; month: string; tier: string;
  initiative: string; keyActions: string; kpi: string; revenueImpact: string;
}
export const ACTION_PLAN: ActionRow[] = [
  { id: 1,  quarter: "Q1", month: "Mar 2026",      tier: "Tier 1: Quick Wins",  initiative: "A. Monthly Subscription Launch",       keyActions: "Build $9.99/mo option in Stripe; update pricing page; add 'Save 50% annual' nudge; A/B test checkout flow",                                      kpi: "Free-to-paid conversion doubles; Monthly sub take rate >30%",              revenueImpact: "$5K-10K/mo incremental" },
  { id: 2,  quarter: "Q1", month: "Mar 2026",      tier: "Tier 1: Quick Wins",  initiative: "B. TikTok/Reels Content Engine",        keyActions: "Create TikTok business account; repurpose 5,000+ videos into 3-5 short-form clips/week; Day 1 vs Day 30; parent reactions; leaderboard spotlights",  kpi: "10K TikTok followers in 90 days; 3-5 posts/week cadence",                  revenueImpact: "Brand awareness / funnel top" },
  { id: 3,  quarter: "Q1", month: "Apr 2026",      tier: "Tier 1: Quick Wins",  initiative: "C. Club Champion Affiliate Program",    keyActions: "Build affiliate dashboard; create referral links; set 20-30% rev share; recruit first 10 coach ambassadors; provide marketing kit",                     kpi: "10 active affiliates; 50 teams onboarded via affiliates",                  revenueImpact: "$2.5K-5K/mo" },
  { id: 4,  quarter: "Q2", month: "May 2026",      tier: "Tier 2: Growth",      initiative: "D. Premium Tier Launch ($99-149/yr)",   keyActions: "Design premium features (personalized plans, AI progress reports, badges, video review); build paywall; beta test with 50 families",                   kpi: "Premium tier adoption >15% of new subs; ARPU increase 40%+",              revenueImpact: "$8K-15K/mo" },
  { id: 5,  quarter: "Q2", month: "Jun 2026",      tier: "Tier 2: Growth",      initiative: "E. Club SaaS Product",                  keyActions: "Rebrand B2B as white-label; build tiered licensing ($500/$1,500/$3,000); club analytics dashboard; branded portals; parent engagement metrics",          kpi: "5 club SaaS contracts signed; Avg deal size $1,500+",                      revenueImpact: "$7.5K+/season" },
  { id: 6,  quarter: "Q2", month: "Jun 2026",      tier: "Tier 2: Growth",      initiative: "F. Seasonal Campaign Calendar",         keyActions: "Map soccer buying cycles; build Meta + Google campaigns for spring prep (Feb-Mar), summer camps (May-Jun); create seasonal landing pages",             kpi: "ROAS >3x on paid campaigns; 500+ new trials per campaign",                 revenueImpact: "$10K-20K/campaign cycle" },
  { id: 7,  quarter: "Q3", month: "Jul 2026",      tier: "Tier 2: Growth",      initiative: "F. Fall Registration Campaign",         keyActions: "Launch Aug-Sep fall season campaign; 'Start training before tryouts'; retarget website visitors; email sequences to leads",                               kpi: "1,000+ new signups Aug-Sep window",                                        revenueImpact: "$15K-25K/campaign" },
  { id: 8,  quarter: "Q3", month: "Aug 2026",      tier: "Tier 3: Long-Term",   initiative: "G. International Expansion Research",   keyActions: "Identify priority markets (UK, Australia, Nigeria, Kenya); research local academies; price sensitivity analysis; localization needs",                     kpi: "Market sizing for top 3 international markets; 5 partnership leads",       revenueImpact: "Future pipeline" },
  { id: 9,  quarter: "Q3", month: "Sep 2026",      tier: "Tier 3: Long-Term",   initiative: "H. Youth Tournament Presence",          keyActions: "Book booth at ECNL or US Club Soccer event; design QR code trial cards; branded giveaways; build tournament landing page",                              kpi: "50+ teams onboarded per tournament; 750+ new players",                     revenueImpact: "$3.75K per tournament" },
  { id: 10, quarter: "Q4", month: "Oct 2026",      tier: "Tier 3: Long-Term",   initiative: "I. AI Virtual Coach (Beta)",            keyActions: "Build upload-and-analyze feature; AI matches clips to drill library; generate personalized improvement plans; beta with 100 families",                  kpi: "Beta NPS >50; 100 beta users; validates premium pricing",                  revenueImpact: "Justifies $149 tier" },
  { id: 11, quarter: "Q4", month: "Nov 2026",      tier: "Tier 2: Growth",      initiative: "F. Holiday Gift Campaign",              keyActions: "Launch 'Give the Gift of Better Soccer' campaign Nov-Dec; gift subscriptions; bundle with merch; Black Friday promo",                                    kpi: "2,000+ gift subs sold; $50K+ holiday revenue",                             revenueImpact: "$50K+ holiday window" },
  { id: 12, quarter: "Q4", month: "Dec 2026",      tier: "Tier 3: Long-Term",   initiative: "G. International Pilot Launch",         keyActions: "Launch in 1-2 priority markets; local pricing ($2/player); partner with 5+ football academies; translated marketing materials",                          kpi: "500+ international players onboarded; 5 academy partnerships",             revenueImpact: "$5K-10K first quarter" },
  { id: 13, quarter: "Q5", month: "Jan 2027",      tier: "Tier 3: Long-Term",   initiative: "I. AI Coach Full Launch",               keyActions: "Full launch of AI virtual coach; integrate into premium tier; marketing push; PR outreach to soccer media",                                              kpi: "1,000+ AI coach users; featured in 3+ soccer publications",                revenueImpact: "$20K+/mo premium uplift" },
  { id: 14, quarter: "Q5", month: "Feb 2027",      tier: "Scaling",             initiative: "Brand Elevation & UX Overhaul",         keyActions: "Professional redesign of platform UX; new brand identity; mobile app optimization; iOS app store launch if not done",                                   kpi: "App store rating >4.5; bounce rate drops 20%+",                           revenueImpact: "Conversion rate uplift" },
  { id: 15, quarter: "Q6", month: "Apr 2027",      tier: "Scaling",             initiative: "Scale Club SaaS to 50+ Clubs",          keyActions: "Dedicated B2B sales outreach; conference attendance; club director webinars; case studies from early adopters",                                        kpi: "50+ club contracts; $150K+ B2B ARR",                                      revenueImpact: "$150K+ ARR" },
  { id: 16, quarter: "Q6", month: "Jun 2027",      tier: "Milestone",           initiative: "$1M+ ARR Target",                       keyActions: "Assess all revenue streams; optimize top performers; cut underperformers; plan for $5M trajectory",                                                     kpi: "Verified $1M+ ARR run rate across all revenue streams",                   revenueImpact: "$1M+ ARR" },
];

// ── Weekly Tasks ─────────────────────────────────────────────────────────────
export interface WeeklyRow {
  week: number; dates: string; quarter: string; focusArea: string;
  tasks: string; deliverables: string; priority: "High" | "Med";
}
export const WEEKLY_TASKS: WeeklyRow[] = [
  { week: 1,  dates: "Mar 3–9",      quarter: "Q1", focusArea: "Monthly Sub Launch Prep",       tasks: "Stripe integration for $9.99/mo; update pricing page wireframes; draft A/B test plan",                                      deliverables: "Stripe config complete",              priority: "High" },
  { week: 2,  dates: "Mar 10–16",    quarter: "Q1", focusArea: "Monthly Sub Launch Prep",       tasks: "Build checkout flow; implement 'Save 50% annual' nudge; QA test payments",                                                   deliverables: "Checkout flow live on staging",       priority: "High" },
  { week: 3,  dates: "Mar 17–23",    quarter: "Q1", focusArea: "Monthly Sub Go-Live",           tasks: "Launch monthly subscription; monitor conversion; fix any payment bugs",                                                       deliverables: "Monthly sub LIVE",                    priority: "High" },
  { week: 4,  dates: "Mar 24–30",    quarter: "Q1", focusArea: "TikTok Setup + Content",        tasks: "Create TikTok business account; plan 4-week content calendar; identify top 20 clips to repurpose",                           deliverables: "TikTok account live; first 3 posts",  priority: "High" },
  { week: 5,  dates: "Mar 31–Apr 6", quarter: "Q1", focusArea: "Content Engine Ramp",           tasks: "Post 5 TikTok/Reels; create Day 1 vs Day 30 template; record 2 parent reaction videos",                                      deliverables: "5 posts published; template created", priority: "Med" },
  { week: 6,  dates: "Apr 7–13",     quarter: "Q1", focusArea: "Affiliate Program Build",       tasks: "Design affiliate dashboard; set up referral link generator; define 20-30% rev share tiers",                                   deliverables: "Affiliate system built",              priority: "High" },
  { week: 7,  dates: "Apr 14–20",    quarter: "Q1", focusArea: "Affiliate Recruitment",         tasks: "Email top 20 coaches/club directors; create ambassador marketing kit; social outreach",                                        deliverables: "10 coaches contacted; kit ready",     priority: "High" },
  { week: 8,  dates: "Apr 21–27",    quarter: "Q1", focusArea: "Affiliate Launch",              tasks: "Launch Club Champion program; onboard first 5 ambassadors; track initial referrals",                                          deliverables: "Program LIVE; 5 ambassadors active",  priority: "High" },
  { week: 9,  dates: "Apr 28–May 4", quarter: "Q1", focusArea: "Content + Affiliate Push",      tasks: "Continue 5 posts/week; first affiliate performance check; optimize top-performing content",                                    deliverables: "Week 4 content report; affiliate check-in", priority: "Med" },
  { week: 10, dates: "May 5–11",     quarter: "Q1", focusArea: "Summer Campaign Prep",          tasks: "Draft summer camp prep campaign; create landing page; design email sequence",                                                  deliverables: "Campaign assets drafted",             priority: "Med" },
  { week: 11, dates: "May 12–18",    quarter: "Q1", focusArea: "Summer Campaign Launch",        tasks: "Launch 'Summer Training Starts Now' campaign; activate Meta ads; email blast to list",                                        deliverables: "Campaign LIVE",                       priority: "High" },
  { week: 12, dates: "May 19–25",    quarter: "Q1", focusArea: "Q1 Review & Optimize",          tasks: "Analyze monthly sub conversion data; review TikTok growth; affiliate pipeline review",                                        deliverables: "Q1 performance report",               priority: "Med" },
  { week: 13, dates: "May 26–Jun 1", quarter: "Q1", focusArea: "Premium Tier Planning",         tasks: "Scope premium features; wireframe personalized training plans; research AI progress report tools",                             deliverables: "Premium tier spec document",           priority: "Med" },
  { week: 14, dates: "Jun 2–8",      quarter: "Q2", focusArea: "Premium Tier Dev Sprint 1",     tasks: "Build personalized plan engine; design badge/certificate system; UI mockups for premium",                                      deliverables: "Sprint 1 deliverables",               priority: "High" },
  { week: 15, dates: "Jun 9–15",     quarter: "Q2", focusArea: "Premium Tier Dev Sprint 2",     tasks: "Implement AI progress reports; build paywall logic; premium onboarding flow",                                                 deliverables: "Sprint 2 deliverables",               priority: "High" },
  { week: 16, dates: "Jun 16–22",    quarter: "Q2", focusArea: "Premium Beta Launch",           tasks: "Invite 50 families to beta; collect feedback; iterate on features",                                                           deliverables: "Beta LIVE with 50 users",             priority: "High" },
  { week: 17, dates: "Jun 23–29",    quarter: "Q2", focusArea: "Premium Beta Iteration",        tasks: "Analyze beta feedback; fix critical issues; prepare launch marketing",                                                         deliverables: "Beta feedback report",                priority: "Med" },
  { week: 18, dates: "Jun 30–Jul 6", quarter: "Q2", focusArea: "Premium Public Launch",         tasks: "Full launch of $99-149/yr premium tier; email announcement; social campaign",                                                 deliverables: "Premium tier LIVE",                   priority: "High" },
  { week: 19, dates: "Jul 7–13",     quarter: "Q2", focusArea: "Club SaaS Scoping",             tasks: "Map white-label requirements; design tiered licensing model; club analytics dashboard wireframes",                             deliverables: "SaaS product spec",                   priority: "High" },
  { week: 20, dates: "Jul 14–20",    quarter: "Q2", focusArea: "Club SaaS Dev Sprint 1",        tasks: "Build club portal framework; implement tiered pricing; branded portal templates",                                              deliverables: "Sprint 1 complete",                   priority: "High" },
  { week: 21, dates: "Jul 21–27",    quarter: "Q2", focusArea: "Club SaaS Dev Sprint 2",        tasks: "Analytics dashboard for directors; parent engagement metrics; club admin tools",                                               deliverables: "Sprint 2 complete",                   priority: "High" },
  { week: 22, dates: "Jul 28–Aug 3", quarter: "Q2", focusArea: "Club SaaS Beta",                tasks: "Pilot with 3 existing club partners; collect director feedback; iterate",                                                      deliverables: "3 clubs on beta",                     priority: "High" },
  { week: 23, dates: "Aug 4–10",     quarter: "Q2", focusArea: "Fall Campaign Prep",            tasks: "Design fall registration campaign; 'Train before tryouts' messaging; build landing pages",                                    deliverables: "Campaign assets ready",               priority: "Med" },
  { week: 24, dates: "Aug 11–17",    quarter: "Q2", focusArea: "Fall Campaign Launch",          tasks: "Launch fall season campaign; activate paid ads; email sequences; retarget website visitors",                                  deliverables: "Fall campaign LIVE",                  priority: "High" },
  { week: 25, dates: "Aug 18–24",    quarter: "Q2", focusArea: "Fall Campaign Optimize",        tasks: "Monitor ROAS; A/B test ad creative; optimize email open rates; scale winning ads",                                            deliverables: "Mid-campaign performance report",     priority: "Med" },
  { week: 26, dates: "Aug 25–31",    quarter: "Q2", focusArea: "Q2 Review + Intl Research",     tasks: "Q2 revenue review; begin international market sizing; identify UK/Australia contacts",                                        deliverables: "Q2 report; market research started",  priority: "Med" },
  { week: 27, dates: "Sep 1–7",      quarter: "Q3", focusArea: "International Market Research", tasks: "Deep dive UK football academy landscape; Australia youth football structure; price sensitivity surveys",                        deliverables: "Market analysis draft",               priority: "Med" },
  { week: 28, dates: "Sep 8–14",     quarter: "Q3", focusArea: "International Outreach",        tasks: "Contact 10 international football academies; explore partnership models; assess localization needs",                           deliverables: "5+ academy conversations",            priority: "Med" },
  { week: 29, dates: "Sep 15–21",    quarter: "Q3", focusArea: "Tournament Prep",               tasks: "Book ECNL/US Club Soccer booth; design booth materials; print QR code trial cards; order giveaways",                          deliverables: "Tournament logistics confirmed",       priority: "High" },
  { week: 30, dates: "Sep 22–28",    quarter: "Q3", focusArea: "Tournament Execution",          tasks: "Attend tournament; demo platform; collect leads; onboard teams on-site",                                                       deliverables: "50+ team leads captured",             priority: "High" },
  { week: 31, dates: "Sep 29–Oct 5", quarter: "Q3", focusArea: "Tournament Follow-Up",          tasks: "Email all tournament leads; personalized follow-up; convert leads to trials; track onboarding",                               deliverables: "Lead nurture sequence sent",           priority: "Med" },
  { week: 32, dates: "Oct 6–12",     quarter: "Q3", focusArea: "AI Coach Research",             tasks: "Evaluate AI video analysis tools; scope MVP features; identify development approach",                                          deliverables: "AI coach feasibility report",          priority: "Med" },
  { week: 33, dates: "Oct 13–19",    quarter: "Q3", focusArea: "AI Coach Dev Sprint 1",         tasks: "Build video upload interface; integrate AI analysis; basic drill matching from library",                                       deliverables: "Upload + basic analysis working",     priority: "High" },
  { week: 34, dates: "Oct 20–26",    quarter: "Q3", focusArea: "AI Coach Dev Sprint 2",         tasks: "Personalized improvement plan generator; UI polish; connect to existing content library",                                      deliverables: "MVP feature complete",                priority: "High" },
  { week: 35, dates: "Oct 27–Nov 2", quarter: "Q3", focusArea: "AI Coach Beta",                 tasks: "Invite 100 families to beta; collect video submissions; monitor AI accuracy; gather feedback",                                deliverables: "Beta LIVE; 100 users",                priority: "High" },
  { week: 36, dates: "Nov 3–9",      quarter: "Q3", focusArea: "Holiday Campaign Prep",         tasks: "Design 'Give the Gift of Better Soccer' campaign; gift subscription flow; merch bundles; Black Friday promo",                  deliverables: "Holiday campaign assets ready",        priority: "Med" },
  { week: 37, dates: "Nov 10–16",    quarter: "Q3", focusArea: "Holiday Soft Launch",           tasks: "Early access email to existing subscribers; social teaser content; influencer outreach",                                      deliverables: "Soft launch emails sent",             priority: "Med" },
  { week: 38, dates: "Nov 17–23",    quarter: "Q3", focusArea: "Black Friday Launch",           tasks: "Full Black Friday / holiday campaign launch; paid ads at scale; email blitz; social push",                                    deliverables: "Campaign LIVE",                       priority: "High" },
  { week: 39, dates: "Nov 24–30",    quarter: "Q3", focusArea: "Black Friday Optimize",         tasks: "Monitor sales; optimize ad spend; extend deals if performing; retarget cart abandoners",                                      deliverables: "Black Friday performance report",     priority: "High" },
  { week: 40, dates: "Dec 1–7",      quarter: "Q4", focusArea: "Holiday Campaign Peak",         tasks: "Peak gift-giving push; last-chance messaging; Cyber Monday extension; influencer posts",                                      deliverables: "Peak revenue week",                   priority: "High" },
  { week: 41, dates: "Dec 8–14",     quarter: "Q4", focusArea: "Holiday Wind Down + Intl Prep", tasks: "Taper holiday campaign; analyze results; finalize international pilot markets and pricing",                                    deliverables: "Holiday recap; intl pilot plan",      priority: "Med" },
  { week: 42, dates: "Dec 15–21",    quarter: "Q4", focusArea: "International Pilot Setup",     tasks: "Set up localized pricing ($2/player); translate key marketing materials; onboard pilot academies",                             deliverables: "Pilot infrastructure ready",           priority: "Med" },
  { week: 43, dates: "Dec 22–28",    quarter: "Q4", focusArea: "Year-End Review",               tasks: "Full year financial review; ARR calculation; initiative ROI analysis; plan Year 2 priorities",                                deliverables: "Annual report; Year 2 plan draft",    priority: "High" },
  { week: 44, dates: "Dec 29–Jan 4", quarter: "Q4", focusArea: "International Pilot Launch",    tasks: "Go live in 1-2 international markets; monitor signups; support pilot academy partners",                                       deliverables: "International pilot LIVE",             priority: "High" },
  { week: 45, dates: "Jan 5–11",     quarter: "Q4", focusArea: "AI Coach Full Launch Prep",     tasks: "Incorporate beta feedback; polish AI features; prepare launch marketing; PR outreach list",                                   deliverables: "Launch-ready AI coach",               priority: "High" },
  { week: 46, dates: "Jan 12–18",    quarter: "Q4", focusArea: "AI Coach Full Launch",          tasks: "Full public launch of AI virtual coach; press release; podcast episode; social campaign",                                     deliverables: "AI Coach LIVE for all users",          priority: "High" },
  { week: 47, dates: "Jan 19–25",    quarter: "Q4", focusArea: "Spring Campaign Prep",          tasks: "Design Feb-Mar spring season prep campaign; 'Get ready for spring tryouts'; update landing pages",                            deliverables: "Spring campaign assets",               priority: "Med" },
  { week: 48, dates: "Jan 26–Feb 1", quarter: "Q4", focusArea: "Brand & UX Overhaul Kickoff",   tasks: "Select design agency; brief on brand refresh; audit current UX; plan mobile app improvements",                               deliverables: "Agency selected; brief delivered",     priority: "High" },
  { week: 49, dates: "Feb 2–8",      quarter: "Q4", focusArea: "UX Redesign Sprint 1",          tasks: "New homepage design; updated pricing page; improved onboarding flow; mobile responsiveness fixes",                             deliverables: "Design mockups approved",             priority: "Med" },
  { week: 50, dates: "Feb 9–15",     quarter: "Q4", focusArea: "Spring Campaign Launch + UX",   tasks: "Launch spring campaign; continue UX overhaul; iOS app store submission if applicable",                                        deliverables: "Spring campaign LIVE",                priority: "High" },
  { week: 51, dates: "Feb 16–22",    quarter: "Q4", focusArea: "Scale Club SaaS Outreach",      tasks: "Dedicated B2B sales push; club director webinars; case study creation from early adopters",                                  deliverables: "5+ new club pipeline",                priority: "Med" },
  { week: 52, dates: "Feb 23–Mar 1", quarter: "Q4", focusArea: "18-Month Review & $1M Check",   tasks: "Comprehensive ARR review; all stream assessment; if <$1M, identify gaps and accelerate; plan $5M trajectory",               deliverables: "18-month performance review",          priority: "High" },
];

// ── Milestones ────────────────────────────────────────────────────────────────
export interface MilestoneRow {
  month: string; theme: string; tierFocus: string;
  milestones: string[]; revenueTarget: string; cumulativeArr: string; dependencies: string;
}
export const MILESTONES: MilestoneRow[] = [
  { month: "Mar 2026", theme: "Foundation Launch",   tierFocus: "Tier 1",    milestones: ["Monthly sub live","TikTok account launched","First 10 short-form videos posted"],                    revenueTarget: "$5K-8K new MRR",    cumulativeArr: "$80K-100K",    dependencies: "Stripe integration; content editor hire" },
  { month: "Apr 2026", theme: "Affiliate Engine",    tierFocus: "Tier 1",    milestones: ["Club Champion program live","10 ambassadors recruited","20+ posts/month cadence"],                   revenueTarget: "$8K-12K MRR",       cumulativeArr: "$100K-140K",   dependencies: "Ambassador recruitment; marketing kit" },
  { month: "May 2026", theme: "Summer Push",         tierFocus: "Tier 1→2",  milestones: ["Summer campaign launched","500+ new trial users","Premium tier spec complete"],                      revenueTarget: "$12K-18K MRR",      cumulativeArr: "$140K-220K",   dependencies: "Paid ad budget; campaign creative" },
  { month: "Jun 2026", theme: "Premium Launch",      tierFocus: "Tier 2",    milestones: ["Premium tier ($99-149) live","50 beta families tested","Club SaaS scoping done"],                    revenueTarget: "$18K-25K MRR",      cumulativeArr: "$220K-300K",   dependencies: "Dev resources for premium features" },
  { month: "Jul 2026", theme: "Club SaaS Build",     tierFocus: "Tier 2",    milestones: ["Club SaaS dev underway","3 pilot clubs on beta","ARPU increasing from premium"],                     revenueTarget: "$22K-30K MRR",      cumulativeArr: "$260K-360K",   dependencies: "Dev sprint capacity; pilot club partners" },
  { month: "Aug 2026", theme: "Fall Campaign",       tierFocus: "Tier 2",    milestones: ["Fall registration campaign live","1,000+ new signups","Club SaaS beta feedback"],                    revenueTarget: "$28K-38K MRR",      cumulativeArr: "$340K-460K",   dependencies: "Ad budget for fall push; club feedback" },
  { month: "Sep 2026", theme: "Tournament + Intl",   tierFocus: "Tier 2→3",  milestones: ["First tournament booth","50+ teams from tournament","International research complete"],               revenueTarget: "$32K-42K MRR",      cumulativeArr: "$380K-500K",   dependencies: "Tournament logistics; travel budget" },
  { month: "Oct 2026", theme: "AI Coach Build",      tierFocus: "Tier 3",    milestones: ["AI coach MVP in development","International pilot plan finalized","Club SaaS onboarding 5+ clubs"],  revenueTarget: "$35K-48K MRR",      cumulativeArr: "$420K-580K",   dependencies: "AI/ML development resources" },
  { month: "Nov 2026", theme: "Holiday Prep",        tierFocus: "Tier 2+3",  milestones: ["Holiday campaign launched","AI coach beta with 100 families","Black Friday promo"],                  revenueTarget: "$45K-60K MRR",      cumulativeArr: "$540K-720K",   dependencies: "Holiday creative; AI beta stability" },
  { month: "Dec 2026", theme: "Holiday Peak + Intl", tierFocus: "Tier 3",    milestones: ["Peak holiday revenue","International pilot live","Year-end review complete"],                         revenueTarget: "$55K-70K MRR",      cumulativeArr: "$660K-840K",   dependencies: "International partnerships; year review" },
  { month: "Jan 2027", theme: "AI + New Year",       tierFocus: "Tier 3",    milestones: ["AI coach full launch","1,000+ AI users","PR coverage in soccer media"],                              revenueTarget: "$60K-78K MRR",      cumulativeArr: "$720K-930K",   dependencies: "AI launch readiness; PR outreach" },
  { month: "Feb 2027", theme: "Brand Refresh",       tierFocus: "Scaling",   milestones: ["UX overhaul underway","Spring campaign live","iOS app optimized"],                                   revenueTarget: "$65K-82K MRR",      cumulativeArr: "$780K-980K",   dependencies: "Design agency; app store approval" },
  { month: "Mar 2027", theme: "Scale Operations",    tierFocus: "Scaling",   milestones: ["50+ club SaaS contracts","Brand refresh complete","International scaling"],                           revenueTarget: "$72K-88K MRR",      cumulativeArr: "$860K-1.05M",  dependencies: "B2B sales capacity" },
  { month: "Apr 2027", theme: "Growth Acceleration", tierFocus: "Scaling",   milestones: ["All revenue streams optimized","$1M ARR in sight or achieved","Plan for $5M trajectory"],           revenueTarget: "$78K-95K MRR",      cumulativeArr: "$940K-1.14M",  dependencies: "Operational capacity to scale" },
  { month: "May–Jun 27", theme: "🎯 $1M+ ARR TARGET", tierFocus: "Milestone", milestones: ["Verified $1M+ ARR run rate","Multiple proven revenue streams","Path to $5M documented"],           revenueTarget: "$83K-100K+ MRR",    cumulativeArr: "$1M+ ARR ✅",  dependencies: "Sustained execution across all tiers" },
];

// ── Revenue Model ─────────────────────────────────────────────────────────────
export interface RevenueRow {
  stream: string; launchMonth: string;
  q1: string; q2: string; q3: string; q4: string;
  yearTotal: string; notes: string; isTotal?: boolean;
}
export const REVENUE_MODEL: RevenueRow[] = [
  { stream: "Existing Annual Subs ($59/yr)",  launchMonth: "Existing",  q1: "$25,000", q2: "$30,000", q3: "$40,000",  q4: "$45,000",  yearTotal: "$140,000", notes: "Organic growth + improved conversion" },
  { stream: "New Monthly Subs ($9.99/mo)",    launchMonth: "Mar 2026",  q1: "$5,000",  q2: "$15,000", q3: "$25,000",  q4: "$35,000",  yearTotal: "$80,000",  notes: "Monthly option reduces commitment friction" },
  { stream: "Premium Tier ($99-149/yr)",      launchMonth: "Jun 2026",  q1: "$0",      q2: "$12,000", q3: "$25,000",  q4: "$35,000",  yearTotal: "$72,000",  notes: "15%+ of new subs choose premium" },
  { stream: "Club Champion Affiliates",        launchMonth: "Apr 2026",  q1: "$3,000",  q2: "$8,000",  q3: "$15,000",  q4: "$20,000",  yearTotal: "$46,000",  notes: "20-30% rev share; 50+ active clubs" },
  { stream: "Club SaaS Licensing",            launchMonth: "Jul 2026",  q1: "$0",      q2: "$7,500",  q3: "$22,500",  q4: "$37,500",  yearTotal: "$67,500",  notes: "$500-$3,000/season tiered" },
  { stream: "Seasonal Campaigns (Paid)",      launchMonth: "May 2026",  q1: "$5,000",  q2: "$20,000", q3: "$50,000",  q4: "$55,000",  yearTotal: "$130,000", notes: "Summer, fall, holiday windows" },
  { stream: "Tournament Revenue",             launchMonth: "Sep 2026",  q1: "$0",      q2: "$0",      q3: "$3,750",   q4: "$7,500",   yearTotal: "$11,250",  notes: "~$3.75K per tournament attended" },
  { stream: "International Markets",          launchMonth: "Dec 2026",  q1: "$0",      q2: "$0",      q3: "$0",       q4: "$5,000",   yearTotal: "$5,000",   notes: "$2/player; pilot in 1-2 markets" },
  { stream: "AI Coach Premium Uplift",        launchMonth: "Jan 2027",  q1: "$0",      q2: "$0",      q3: "$0",       q4: "$20,000",  yearTotal: "$20,000",  notes: "Justifies $149 premium pricing" },
  { stream: "Merch & Bundles",               launchMonth: "Nov 2026",  q1: "$0",      q2: "$0",      q3: "$5,000",   q4: "$15,000",  yearTotal: "$20,000",  notes: "Holiday bundles; branded training gear" },
  { stream: "TOTAL",                          launchMonth: "",          q1: "$38,000", q2: "$92,500", q3: "$186,250", q4: "$275,000", yearTotal: "$591,750", notes: "Projected ARR (Year 1 annualized): $591,750", isTotal: true },
];

// ── 12-Month Action Plan ──────────────────────────────────────────────────────
export interface Action12Row {
  id: number; phase: string; category: string;
  initiative: string; action: string; successMetric: string; timing: string;
}
export const ACTION_PLAN_12: Action12Row[] = [
  { id: 1,  phase: "Phase 1: Foundation",  category: "Audience",     initiative: "Audit email list",                   action: "Segment leads by source; tag Soccer Near Me, podcast, Facebook",                              successMetric: "Clean list ready",              timing: "M1–M2" },
  { id: 2,  phase: "Phase 1: Foundation",  category: "Audience",     initiative: "Build email nurture sequence",        action: "7-email flow: free content → problem → solution → testimonial → CTA",                          successMetric: "Sequence live",                 timing: "M1" },
  { id: 3,  phase: "Phase 1: Foundation",  category: "Conversion",   initiative: "High-converting landing page",        action: "Add social proof, free trial CTA, countdown/urgency element (anytimecamps-style)",              successMetric: "LP live + tracked",             timing: "M1" },
  { id: 4,  phase: "Phase 1: Foundation",  category: "Distribution", initiative: "AST CTA on every Soccer Near Me page", action: "Banner + inline CTA on all club/team listing pages",                                         successMetric: "+200 leads/mo from SNM",         timing: "M1–M2" },
  { id: 5,  phase: "Phase 1: Foundation",  category: "Podcast",      initiative: "Trackable promo code every episode",   action: "Unique code per episode; track in Stripe",                                                   successMetric: "Baseline conversion %",         timing: "M1" },
  { id: 6,  phase: "Phase 1: Foundation",  category: "Teams",        initiative: "Build target list of 50 clubs/coaches", action: "Pull from Facebook groups + Soccer Near Me club directory",                                 successMetric: "List ready",                    timing: "M2" },
  { id: 7,  phase: "Phase 1: Foundation",  category: "Teams",        initiative: "Outreach 10 clubs/coaches per week",  action: "Personalized email/DM via GHL sequence",                                                     successMetric: "3–5 pilots signed M1–M3",       timing: "M2–M3" },
  { id: 8,  phase: "Phase 2: Scale",       category: "Content",      initiative: "Publish 4 SEO articles/month",        action: "Target 'youth soccer training at home' keywords on AST blog",                                 successMetric: "+500 organic leads/mo",         timing: "M4–M6" },
  { id: 9,  phase: "Phase 2: Scale",       category: "Distribution", initiative: "Launch referral program",             action: "In-app share link; reward = 1 free month",                                                   successMetric: "50+ referrals/mo",              timing: "M4" },
  { id: 10, phase: "Phase 2: Scale",       category: "Teams",        initiative: "Recruit 2–3 regional sales reps",     action: "Commission: 20% recurring on subs they close",                                               successMetric: "3 active reps by M6",           timing: "M4–M5" },
  { id: 11, phase: "Phase 2: Scale",       category: "Revenue",      initiative: "Launch The Parent-Trainer's Playbook", action: "Pre-sell via email list; price at $25",                                                      successMetric: "$2K+ launch revenue",           timing: "M5" },
  { id: 12, phase: "Phase 2: Scale",       category: "Pricing",      initiative: "Test premium individual tier ($99/yr)", action: "Bundle: plan builder AI + 1 live Q&A/month",                                               successMetric: "10% upgrade rate",              timing: "M5–M6" },
  { id: 13, phase: "Phase 2: Scale",       category: "Ads",          initiative: "Launch paid Facebook/Instagram campaign", action: "$500/mo budget; target soccer parents 28–45",                                             successMetric: "Positive ROAS by M6",           timing: "M5" },
  { id: 14, phase: "Phase 3: Optimize",    category: "Analytics",    initiative: "Weekly Stripe dashboard review",      action: "Track MRR, new subs, churn, net income vs target",                                           successMetric: "Monthly cadence locked",        timing: "M7+" },
  { id: 15, phase: "Phase 3: Optimize",    category: "Retention",    initiative: "Build win-back email sequence",       action: "Auto-trigger at 60 days before renewal",                                                     successMetric: "Reduce churn by 5%+",           timing: "M7" },
  { id: 16, phase: "Phase 3: Optimize",    category: "Content",      initiative: "Double down on best-performing channel", action: "Pick top channel from M1–M6 data; 2x output",                                             successMetric: "Lead volume doubles",           timing: "M7–M9" },
  { id: 17, phase: "Phase 3: Optimize",    category: "Teams",        initiative: "Target club-level deals (50+ players)", action: "Offer annual club pricing; close 1–2 per month",                                            successMetric: "+2 club deals/mo",              timing: "M8–M12" },
  { id: 18, phase: "Phase 3: Optimize",    category: "Revenue",      initiative: "Evaluate monthly plan option",        action: "Monthly at ~$7.99; increases accessibility",                                                 successMetric: "Test conversion lift",          timing: "M9" },
  { id: 19, phase: "Phase 3: Optimize",    category: "Exit Check",   initiative: "Monthly gap analysis vs target",      action: "See Revenue Model tab — GAP row",                                                            successMetric: "GAP turns positive",            timing: "Monthly" },
  { id: 20, phase: "Phase 3: Optimize",    category: "Exit Check",   initiative: "When GAP is positive 3 months",       action: "Give WGNSTAR notice — execute the transition",                                               successMetric: "YOU ARE OUT ✅",               timing: "M10–M12" },
];

// ── Monthly Milestone Tracker ─────────────────────────────────────────────────
export interface MilestoneTrackerRow {
  mo: number; month: string; keyMilestone: string;
  subsTarget: number; netRevTarget: number;
}
export const MILESTONE_TRACKER: MilestoneTrackerRow[] = [
  { mo: 1,  month: "Month 1",  keyMilestone: "Landing page live; nurture sequence running; 10 club outreach emails sent",     subsTarget: 50,   netRevTarget: 300 },
  { mo: 2,  month: "Month 2",  keyMilestone: "SNM CTA live; 20 clubs contacted; first team pilot signed",                     subsTarget: 120,  netRevTarget: 720 },
  { mo: 3,  month: "Month 3",  keyMilestone: "3 active team pilots; referral program planned",                                 subsTarget: 200,  netRevTarget: 1200 },
  { mo: 4,  month: "Month 4",  keyMilestone: "Referral program live; SEO content publishing; rep #1 recruited",               subsTarget: 300,  netRevTarget: 1800 },
  { mo: 5,  month: "Month 5",  keyMilestone: "Book pre-launch email sent; premium tier tested",                                subsTarget: 420,  netRevTarget: 2520 },
  { mo: 6,  month: "Month 6",  keyMilestone: "Book launched; 2 active reps; paid ads profitable",                             subsTarget: 560,  netRevTarget: 3360 },
  { mo: 7,  month: "Month 7",  keyMilestone: "Win-back sequence live; identify top acquisition channel",                       subsTarget: 720,  netRevTarget: 4320 },
  { mo: 8,  month: "Month 8",  keyMilestone: "Club-level deals pursued; double down on top channel",                          subsTarget: 900,  netRevTarget: 5400 },
  { mo: 9,  month: "Month 9",  keyMilestone: "Monthly plan option tested; MRR trending toward target",                         subsTarget: 1100, netRevTarget: 6600 },
  { mo: 10, month: "Month 10", keyMilestone: "GAP check — are you within range of exit?",                                     subsTarget: 1300, netRevTarget: 7800 },
  { mo: 11, month: "Month 11", keyMilestone: "Second consecutive positive GAP month",                                          subsTarget: 1500, netRevTarget: 9000 },
  { mo: 12, month: "Month 12", keyMilestone: "DECISION POINT: Exit if GAP positive 3 months",                                 subsTarget: 1700, netRevTarget: 10200 },
];
